indent: *.c
	indent -kr -i8 -ts8 -l80 -sob -ss -bs-linux *.c	
Lab2: Lab2.c
	gcc -Wall -g -std=c99 Lab2.c -o Lab2 && ./Lab2 < custom.txt
Lab1: Lab.c
	gcc -Wall -g -std=c99 Lab.c -o Lab1 && ./Lab1 < custom.txt
clean: 
	rm Lab2 Lab1 
