indent: ./Source/*.c
	indent -nbad -bap -nbc -bbo -hnl -br -brf -c33 -cd33 -ncdb -ce -ci4 -cli0 -d0 -di1 -nfc1 -i8 -ip0 -l180 -lp -npcs -nprs -npsl -sai -saf -saw -ncs -nsc -sob -nfca -cp33 -ss -ts8 -il1 ./Source/*.c	
Lab: ./Source/Lab.c 
	gcc -Wall -std=gnu99 ./Source/Lab.c -o Lab 
clear: 
	rm Lab 
